### ISSUE TITLE
not working in iOS

### ISSUE THREAD

**Issue by mohkh** [Kidoz-SDK/KIDOZ_Unity_SDK_Example#3]
banner add not working on iOS and when try to show interstitial ad the app crash
I tested th demo from kidoz .

**Comment by RinaKidoz** [comment]
Hello,

Currently we are optimizing our iOS plugin, once the new version will be released we will notify you.

In the meantime, please start adding our sdk to your Android apps.

Thanks,
Rina

**Comment by mohkh** [comment]
Thanks for reply...
Im wating and please dont forget to add parental control support.

**Comment by mohkh** [comment]
Hello.

*Sorry about my english*

1- i want to ask about KIDOZ SDK for Unity iOS. When you expect the
developers release it ?
2-Did KIDOZ earn good money from Arab countries(because the 95% of ads will
be shown in Arab countries) ?

thanks

**Comment by mohkh** [comment]
Dear Madam,

I sent email to you before 5 months and  until now you didn't answer me.

However, I enquire information about kidoz sdk for iOS. Is sdk ready to use
with ios?

Yours faithfully
Mohammad Alkhalailah

**Comment by RinaKidoz** [comment]
Hi Mohammad,

Sorry for the inconvenience.

We have released the new iOS SDK version for beta testers, and currently
preparing a new version based on their feedback.

The sdk should be ready in a week or so. I will keep you updated on the
progress.

Please feel free to contact me directly, if you have any questions.

Kind Regards,
Rina


*Rina Zholobova*
KIDOZ, Head of Publisher Relations
Skype: rina_kidoz
Mobile: +972-544-538445

**Comment by mohkh** [comment]
Hi

*Sorry about my english*

what about kidoz sdk for unity ios ?
its now 2 weeks since your last reply.

Kind Regards,

**Comment by mohkh** [comment]
Hi

*Sorry about my english*

what about kidoz plugin for unity iOS?
its now more than 2 weeks since your last reply.

Kind Regards,

**Comment by ronen-k** [comment]
unity iOS is supported while ago on this plugin.

**Comment by RinaKidoz** [comment]
Hi Mohammad,

Sorry for the delay.

You can check the documentation for iOS Unity plugin:
https://github.com/Kidoz-SDK/KIDOZ_Unity_SDK_Example

Please let us know if you have any questions.

Best,
Rina
