### ISSUE TITLE
Duplicate class issue

### ISSUE THREAD

**Issue by viche72** [Kidoz-SDK/KIDOZ_Unity_SDK_Example#9]
Hi,
I just downloaded the latest SDK and imported the Unity package into an existing project. When building the project I'm getting numerous error regarding duplicate files which all point to the android-support-v4.jar found in the KidozSDK/libs/ folder. Is this a know issue and is there a solution for it.

Thanks,

**Comment by ronen-k** [comment]
Hi,
Please remove the android-support-v4.jar from your project as it is not required anymore.
We will delete also from the repository.

Thanks,

**Comment by viche72** [comment]
Thanks that worked.
________________________________
